# External gems
gems:
 # - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: Eye Division
subtitle: Web development in Bath and Oxford
name: Eye Division
description: Web site for Eye Division Ltd
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.eyedivision.com/" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"
email: info@eyedivision.com


# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
permalink: pretty

# Image CDN
imagecdn:
  #staging: "http://ed-dev.imgix.net"
  production: "https://ed-eyedivision.imgix.net"


# Collections
collections:
    clients:
        output: true
        permalink: /clients/:path/


# Defaults Example
defaults:
    -
        scope:
            path: ""
            type: "clients"
        values:
            layout: "client"
            logo: /assets/eyedivision-logo.png

# Disqus comments
# disqus_shortname:

# Google analytics
ga_tracking_id: UA-964773-1

#Google Recaptcha for contact form
recaptcha_site_key: 6LdQIxUUAAAAAJAiUwXz-IFIZldyn-TEB0dLU0h6

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
#


social:
  - name: Twitter
    icon: icon-twitter_sign
    username: EyeDivision
    url: https://twitter.com/EyeDivision
    desc: Follow us on Twitter
    share: true

  - name: Facebook
    icon: icon-facebook_sign
    username: eyedivision
    url: https://www.facebook.com/eyedivision
    desc: Like us on Facebook
    share: true

  - name: LinkedIn
    icon: icon-linkedin-alt
    username: #eyedivision
    url: #https://www.linkedin.com/company/eye-division-ltd
    desc: Connect with us on LinkedIn
    share: true


  - name: Instagram
    icon: icon-instagram
    username: #eyedivision
    url: #https://instagram.com/eyedivision
    desc: Follow me on Instagram
    share: false


# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/images/clevedon_pools.jpg"
    fb_image_width: 2048
    fb_image_height: 1156
    fb_image_type: "image/jpeg"

    twitter_image: "assets/eyedivision-logo.png"

